---
version: 3
dependencies:
  python_interpreter:
    package_system: python312
  python: requirements.txt
  galaxy: requirements.yml
  system: bindep.txt
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:latest
